### ISSUE TITLE
Intake Quota, picking 8:00 AM produces error

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#101]
ENVIRONMENT
Windows 10 Chrome
ISSUE
Error message:”Please select one of the "time of day" options.”
WHAT PAGE
Conference Administrative Pages: Intake: Quantity of Requests Accepted (Quota): 
[Intake Quota.docx](https://github.com/josephr5000/confdb-public/files/448340/Intake.Quota.docx)
Intake: Quota
WHAT STEPS WHERE TAKEN
I changed the selection to “Weekly”, the Take to “25”, and the starting day to “Tuesday”, the time to “8:00 AM” and clicked “Save”.
WHAT I EXPECTED
I expected the record to be saved.
WHAT HAPPENED
Got the error message above. **This happens only when the “8:00 AM” time of day is selected.**

Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18147798/1adedd5a-6f8b-11e6-9990-7a21f16370e5.png)

**Comment by TomOwens5000** [comment]
I noticed this too. Another issues, I got a crashed message but am not sure what I did and so far cannot duplicate the problem.

**Comment by drodruck** [comment]
Also, found if we pick Monday for the weekly choice, the error message "Please select one of the "day of week" options." comes up.

**Comment by josephr5000** [comment]
FIXED

**Comment by josephr5000** [comment]
FYI @drodruck I was enabling/disabling availability of a blank first-line choice depending whether you were establishing quota settings for the very first time or editing pre-existing settings, but the validation didn't realize this and complained any time you picked the first choice.

I chose the easiest solution, which is to always permit a blank first choice, and then validation complains if you have a quota choice where that matters.  Eg: for unlimited it doesn't matter so validation shouldn't complain.  For daily, the day-of-week choice doesn't matter so validation shouldn't complain.

**Comment by drodruck** [comment]
Your solution works for Weekly and Daily for time of day and day of week but it still doesn't work for Monthly time of day. I noticed the drop down choices look different for Monthly, no blank choice at the top of the list.

**Comment by josephr5000** [comment]
Oops, FIXED that.  Thanks!

**Comment by drodruck** [comment]
Yep, works now.
