### ISSUE TITLE
Issue On Current Live Site - cannot upload files to the Document Library

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#289]
Program will not permit uploading a file to the Document Library.

![capture](https://cloud.githubusercontent.com/assets/20777996/19581951/c71f6838-96e5-11e6-8481-7eaa89079d37.JPG)

This may not be a problem for OLG starting next Monday but it WILL be a problem for any other Conference not on the new version of the software.

**Comment by josephr5000** [comment]
FIXED.  Was a directory permissions issue.  Would you please check it?  Thanks.

**Comment by TomOwens5000** [comment]
Still broken.
Tried first this time to create a new folder.
Got this error message.
![capture](https://cloud.githubusercontent.com/assets/20777996/19583004/f6abeb46-96ed-11e6-887a-c34ec138ccfe.JPG)
Then tried just uploading a file all by itself. Same error message.

**Comment by josephr5000** [comment]
I was just restarting the site.  That should have been temporary.

**Comment by TomOwens5000** [comment]
I wonder if the change you made didn't take effect immediately before.
Just tried again and I can create both a folder and a file.
Closing as FIXED.
Tom

**Comment by TomOwens5000** [comment]
Just tried again. I don't get an error message.
Everything progresses as expected but the file does NOT show up in the library.
Was trying this time to upload last months Treasurer report into that Doc Lib directory.

**Comment by josephr5000** [comment]
This bug was filed for the old site.  In your comment above are you referring to the old or the new site?

**Comment by TomOwens5000** [comment]
New Site
 

    On Friday, November 4, 2016 10:35 AM, josephr5000 <notifications@github.com> wrote:
 

 This bug was filed for the old site. In your comment above are you referring to the old or the new site?—

**Comment by josephr5000** [comment]
Okay.  This bug is about the old site.  The new site's issue has already been reported by you (#305) which duplicated an earlier report by me (#299).  Let's leave this one closed.
