### ISSUE TITLE
CC bug - expected wait time returning "True" instead of "hours"

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#310]
This worked before but must have gotten broken.

![capture](https://cloud.githubusercontent.com/assets/20777996/20239777/bece9b38-a8bd-11e6-8aef-d870f34833da.PNG)

**Comment by josephr5000** [comment]
FIXED

**Comment by TomOwens5000** [comment]
NOT FIXED!
Just tried it again at ~11:35 am today - Monday.
https://confdb-test.azurewebsites.net/confdb/ClientView.asp?ClientID=87694
I don't have access to the LIVE Call Center site so I can't check it there.
Tom

**Comment by josephr5000** [comment]
Oh, I didn't fix it on TEST.  I have just now.  Please re-try.

**Comment by TomOwens5000** [comment]
Just retested.
Fixed and closing.
Tom
