### ISSUE TITLE
Record Website Feedback

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#83]
Sent following message. Have not heard anything back. Wondering if the feature in broken or Joseph has just not seen it yet.
![screen-10 30 50 27 08 2016](https://cloud.githubusercontent.com/assets/20777996/18029024/5d5f3122-6c41-11e6-8116-a8889ed2f1f4.png)

**Comment by josephr5000** [comment]
Marking as a bug.  No, I didn't receive any message (yet).  Yahoo has been a bit slow, so we'll see if it shows up...

**Comment by josephr5000** [comment]
Checked sendgrid.com, the service ConfDB uses to deliver email.  It shows a log entry for an email from exk7rsc@yahoo.com dated 8/25/16 that could have been this.  Problem might be on the receiving end (mine) rather than in the site.

**Comment by TomOwens5000** [comment]
Still appears to not be working as of 8/30/16.

**Comment by josephr5000** [comment]
Okay, thanks, I'll investigate further.

**Comment by TomOwens5000** [comment]
Found additional bug.  The data timestamp is not recognizing the proper date and time.  Neither one of them match the computer clock. This DOES work correctly in the current version.

**Comment by josephr5000** [comment]
What does this have to do with recording websight feedback not working?

If nothing, please open a separate bug instead.  If something, please clarify as I'm not following.

FYI I think Doug already filed a bug about timezones being off by 7/8 hours.  If that's what you're seeing, you can skip filing a separate bug as it's already covered.

**Comment by TomOwens5000** [comment]
Probably nothing to do with the feedback not getting to you as such.
I was just pointing out that the screen itself has a date problem.
Probably the same issue as Doug mentioned but I don't know if they are separate bugs (you not getting the feedback or the time being off, which I think might be a separate issue.
Hope that clarifies it.  I will leave the comment here rather than open a new issue.  If you feel it is a different issue that should be reported differently, please do so.

![xxxxx](https://cloud.githubusercontent.com/assets/20777996/18201277/1e15f89e-70be-11e6-97d3-dadef0417901.png)

**Comment by josephr5000** [comment]
FIXED the email problem.

**Comment by josephr5000** [comment]
FIXED the time problem too :-)

**Comment by TomOwens5000** [comment]
Still not working. Clicked on Save button. Got the following response: The page cannot be displayed because an internal server error has occurred.

![screen-07 25 48 19 09 2016](https://cloud.githubusercontent.com/assets/20777996/18635702/c611f62c-7e3a-11e6-9737-61adf8025b12.png)
The page cannot be displayed because an internal server error has occurred.

**Comment by josephr5000** [comment]
Oops, typo.  Should work now.

Also, fixed the button name.
