### ISSUE TITLE
Document Library

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#85]
Broken (links I presume). All folders open as expected. Drilling down to the contents of each folder also works as expected. Clicking on any listed file does NOT work. Message: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

The one folder that had nothing in it worked - but there was nothing there to select.

**Comment by josephr5000** [comment]
Related to #7

**Comment by josephr5000** [comment]
Assigning to @TomOwens5000 and @drodruck for testing.

**UPLOAD/DOWNLOAD OF NEW FILES - FIXED FOR ALL.**

**OLD FILES MIGRATED FOR**
- ST JAMES
- OL GUADALUPE
- MARY QUEEN OF PEACE.
- HOLY ROSARY

The look should be the same, but the back-end is completely rewritten to store files in Azure Blob Storage instead of on the server hosting the web pages.

Please thoroughly test file upload, viewing uploaded and existing files, and deleting files.

Try unusual filenames, blank names, very long names, names with odd characters, etc.

Try empty files.  Try regular files.  Try big files.

Try PDF, Word, Excel, plain text, pictures, and anything else your conference uploads.

Thanks!

**Comment by TomOwens5000** [comment]
Tried again. Two tests: one, tried to open a file contained in a file folder; and, two, tried to open a stand-alone file (one not contained in a file folder). Got the following message in both instances.

<Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:85877e6c-0001-006f-6710-0e98a2000000
Time:2016-09-13T22:47:44.0607865Z</Message></Error>

**Comment by drodruck** [comment]
ENVIRONMENT
Windows 10 Pro, Chrome
ISSUE
Document Library
WHAT PAGE
Document Library 
WHAT STEPS WHERE TAKEN
Uploaded four documents to view in our Document Library, our Minutes subdirectory, and the Unapproved Minutes subdirectory to the Minutes directory
WHAT I EXPECTED
Expected to view the pdf and .doc documents
WHAT HAPPENED
Got the following message for all documents and directories:
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18496262/6f31565a-79d9-11e6-8c82-b9a5d0a518bb.png)

**Comment by drodruck** [comment]
Chrome and Firefox have the same message.
This is the message in Edge if it helps:
![image](https://cloud.githubusercontent.com/assets/20655031/18496472/07868ce4-79db-11e6-921f-b63fdbf19290.png)

**Comment by josephr5000** [comment]
@drodruck @TomOwens5000 Would you both please try again and let me know if your problem is fixed?

I think it was a permissions setting that I forgot to set in Azure Storage.  By default it's set to keep contents private, so your files were uploaded fine but you lacked permissions to read them.  As a security measure it doesn't reveal that it's a permissions problem -- it just pretends that what you requested doesn't exist.  I adjusted the permissions so you should now have read access.

**Comment by drodruck** [comment]
Got it to fail! I tried to upload "Frederick Ozanam- a life in letters.pdf" a 8,137 kb file and got:
![image](https://cloud.githubusercontent.com/assets/20655031/18523490/4ba14f8e-7a69-11e6-8b51-6eec28992083.png)

**Comment by drodruck** [comment]
Got the same with a 5,000+ KB file but succeeded in uploading a 1,713 KB file.

**Comment by drodruck** [comment]
I have tried every file extension I have and some weird names, like A History of Rome to 565 A D-asin_B004TS0ILA-type_EBOK-v_0.azw, and the only problem I ran into was the size of file mentioned above.  It appears the size limit is between 4,049 KB and 4,378 KB.

**Comment by TomOwens5000** [comment]
Same results this morning as Doug listed above.
Tried to view our Conference Manual (3,910 KB) - Same Server Error he shows above.
Tried to upload and view the same file. Same Server Error he shows above.
Tested Word Documents, PDFs, Power Point Presentation (404 KB) - worked as expected.
All files under 1,000 KB worked as expected, EXCEPT the following.
     Tested Excel Sheet (Utility Pledge Template.xlsx - 20.5 KB). It gave the following error:
<Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:cc6bd2c0-0001-00d6-1867-0f7bac000000
Time:2016-09-15T15:38:12.2262609Z</Message></Error>

**Comment by josephr5000** [comment]
@TomOwens5000 Could you clarify what you were *doing* with that Excel sheet before you got the error?  Did you upload it yesterday?  Or had it been there for months and you're now trying to download it?  Did you get the error while trying to upload it, or while trying to download it?  Thanks.

**Comment by josephr5000** [comment]
@TomOwens5000 ...and can you reproduce that error consistently with the Excel sheet?  If so, please list the steps, and email me the file so I can investigate.

**Comment by TomOwens5000** [comment]
The above message what I got when I just tried again to open the Excel 
sheet. The file has been on the website all along (not uploaded 
recently). Works fine our the LIVE Conference website. I think it has 
worked before here on the Beta site.  The steps taken: just clicked on 
the file in the Documents Library to active the sheet. No other steps taken.

**Comment by TomOwens5000** [comment]
Out of curiosity … tried to upload the same Excel file to see what happens. It won’t upload. Don’t know if that helps or not. Tried the same thing in the Live version and it DOES work.

**Comment by josephr5000** [comment]
FIXED.  Would you please try again?  I republished the upload code yesterday but had it pointed to the development database so the file index you were *seeing* didn't match the index available to the upload code.  Should now match and behave better.

**Comment by TomOwens5000** [comment]
Yes, the Excel sheet now does 2 things: 1, it works and, 2, i can upload it from its source.

Still broken. Large files still crash it (same comments above by Doug and me).
Still broken. Does not display the path underneath the filename.
Still broken. Doe not allow editing the filename (same result as described above).

**Comment by josephr5000** [comment]
That's one challenge with having a single issue (like this) that really addresses multiple different problems.  It can get hard to keep track of all of them.

On your three points above:

1. SEPARATE ISSUE COMING.  Got it. Forgot about that. Would really benefit from having its own issue which I'll open in a moment.
2. BY DESIGN. The path didn't strike me as being particularly helpful so I removed it.  The resulting list is a lot cleaner in appearance.  Displaying the path or not has no bearing on functionality.
3. NEWS TO ME.  I must have missed something, but that's the first I've heard that you're having an issue editing the filename.  Please open a separate issue and explain what name you tried and what happened.

Thanks, and closing this issue as the fundamental problem is covered and other problems will be covered separately.
